baseURL = "https://mende.io"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Tobi(as Mende)"
theme = "lightbi-hugo"
metaDataFormat = "toml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Config.Services.Disqus]
Shortname = "mende-2"
[Params]
selfHosted = true
mainSections = ["blog"]
dateFormat = "02 January 2006"
comments = true
readingTime = true
wordCount = false
useHLJS = true
socialShare = true 
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = false
description="Consultant. Speaker. Coach. Diver. Nomad."
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "Tobias Mende"
  website = "https://mende.io"
  authorInfo = "I help software companies develop better software faster, creating win-win-win scenarios for businesses, customers, and employees. With over 15 years in product, engineering, and organizational development, I empower leaders to build high-performing teams in tech."
  authorPostImage = "/img/profilbild-square.jpg"
  email = "tobi@techunicorn.builders"
  instagram = "tobias_mende"
  linkedin = "tobiasmende"
  github = "TobiasMende"
  gitlab = "TobiasMende"
  mastodon = "https://mastodon.social/@tobias_mende"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.footer]]
    name = "Imprint"
    url = "/imprint"
    weight = 1

[[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy"
    weight = 2

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

